### ISSUE TITLE
This shouldn't exist in the first place

### ISSUE THREAD

**Issue by smakosh** [Stormix/Stormix#1]

**Comment by smakosh** [comment]
@Stormix

**Comment by Stormix** [comment]
Hmmm, interesting suggestion, can you make a pull request? @smakosh

**Comment by steebchen** [comment]
XD

**Comment by smakosh** [comment]
> Hmmm, interesting suggestion, can you make a pull request? @smakosh

we can't sadly raise a PR that deletes the repository

**Comment by Stormix** [comment]
Can't wait to open the same issue when you finally give in.
